name: weatherapp
description: "A weather app with news and forecast features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0-278.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Required for your weather/news functionality
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.6
  share_plus: ^7.2.1

  # Location & Storage
  geolocator: ^12.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
